### ISSUE TITLE
TV shows no answer, also the house icon is wrong (external accessory)

### ISSUE THREAD

**Issue by Staubgeborener** [konradknitter/homebridge-philips-android-tv#1]
**Describe The Bug:**
Philips TV shows 'no answer' in Homekit as an external accessory (in the top bar) - TV can however be controlled via Homekit. But here the icon is wrong. It should actually be a TV icon and not a house icon, since it is an external accessory in your code.

**To Reproduce:**
Download plugin, set up the config, go to `Homekit -> add Device -> I don't have a code / i can't scan -> click the new TV`

**Logs:**

```
[2020-11-2 20:36:16] Got SIGTERM, shutting down Homebridge...
[2020-11-2 20:36:16] [Homebridge UI] Failed to refresh characteristics for PhilipsAndroidTV: socket hang up
[2020-11-2 20:36:16] [Homebridge UI] Failed to refresh characteristics for PhilipsAndroidTV: socket hang up
[2020-11-2 20:36:16] [Homebridge UI] Failed to refresh characteristics for PhilipsAndroidTV: socket hang up
[2020-11-2 20:36:16] [Homebridge UI] Failed to refresh characteristics for PhilipsAndroidTV: socket hang up
[2020-11-2 20:36:21] [Hue] goodbye
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
Stopped Node.js HomeKit Server.
homebridge.service: Found left-over process 1297000 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
homebridge.service: Found left-over process 1297533 (sudo) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
homebridge.service: Found left-over process 1297535 (journalctl) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
homebridge.service: Found left-over process 1298145 (sudo) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
homebridge.service: Found left-over process 1298146 (systemctl) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started Node.js HomeKit Server.
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
[2020-11-2 20:36:22] Loaded config.json with 4 accessories and 9 platforms.
[2020-11-2 20:36:22] ---

...

[2020-11-2 20:36:26] ---
[2020-11-2 20:36:26] Loaded plugin: homebridge-philips-android-tv@0.1.3
[2020-11-2 20:36:26] Registering accessory 'homebridge-philips-android-tv.PhilipsAndroidTV'
[2020-11-2 20:36:26] ---
[2020-11-2 20:36:26] Loading 9 platforms...
[2020-11-2 20:36:26] [Config] Initializing config platform...
[2020-11-2 20:36:26] [Config] Spawning homebridge-config-ui-x with PID 1298254
[2020-11-2 20:36:27] [PhilipsAndroidTV] Initializing PhilipsAndroidTV accessory...
[2020-11-2 20:36:27] [PhilipsAndroidTV] Switch finished initializing!
[2020-11-2 20:36:27] PhilipsAndroidTV 81F5 is running on port 36641.
[2020-11-2 20:36:27] Please add [PhilipsAndroidTV 81F5] manually in Home app. Setup Code: 031-45-154

[2020-11-2 20:36:27] [PhilipsAndroidTV] { component: { packageName: 'NA', className: 'NA' } }
[2020-11-2 20:36:27] [PhilipsAndroidTV] Available Channels:
[2020-11-2 20:36:27] [PhilipsAndroidTV] {}
[2020-11-2 20:36:27] [PhilipsAndroidTV] [
  {
    enum_id: 1,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_PERSONAL'
  },
  {
    enum_id: 2,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_VIVID'
  },
  {
    enum_id: 3,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_NATURAL'
  },
  {
    enum_id: 4,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_STANDARD'
  },
  {
    enum_id: 5,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_MOVIE'
  },
  {
    enum_id: 6,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_GAME'
  },
  {
    enum_id: 14,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_MONITOR'
  },
  {
    enum_id: 13,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_PERSONAL'
  },
  {
    enum_id: 9,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_VIVID'
  },
  {
    enum_id: 20,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_DOLBY_VISION_BRIGHT'
  },
  {
    enum_id: 21,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_DOLBY_VISION_DARK'
  },
  {
    enum_id: 10,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_NATURAL'
  },
  {
    enum_id: 11,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_MOVIE'
  },
  {
    enum_id: 12,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_HDR_GAME'
  },
  {
    enum_id: 7,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_ISF_DAY'
  },
  {
    enum_id: 8,
    string_id: 'org.droidtv.ui.strings.R.string.MAIN_ISF_NIGHT'
  }
]

...

Setup Payload:
```

**Plugin Config:**

```json
        {
            "accessory": "PhilipsAndroidTV",
            "name": "PhilipsAndroidTV",
            "ip": "192.168.178.XX",
            "macAddress": "XX:XX:XX:XX:XX:XX",
            "apiUser": "XXXXXXXXXX",
            "apiPass": "XXXXXXXXXXXXXXXXXXXX"
        },
```

**Screenshots:**
![IMG_7869](https://user-images.githubusercontent.com/28908603/97910976-da2b7a80-1d4a-11eb-8122-a7067b30aeda.jpg)
![IMG_7870](https://user-images.githubusercontent.com/28908603/97911889-49ee3500-1d4c-11eb-867e-743ded037681.jpg)

**Environment:**

* **Plugin Version**: 0.1.3
* **Homebridge Version**: 1.2.3
* **Node.js Version**: 14.15.0
* **NPM Version**: 6.14.8
* **Operating System**: Arch Linux, no docker

Keep up the good work!

**Comment by konradknitter** [comment]
Hi,

Thanks for reporting.
I didn’t know about this way to add device. :) 
I will check it out in next days.

**Comment by Staubgeborener** [comment]
To put you in the picture: Since iOS 14, televisions no longer have a TV icon but a house icon. To get around this you have to integrate the TV as an `external accessory` (as you already have it in your code) - this way you can add it via `homekit -> add device` and 'normally' it would then also have the old TV icon back again. These two plugins seem have this problem solved like this, if you want to watch inside the code:
1. [homebridge-bravia](https://www.npmjs.com/package/homebridge-bravia)
2. [homebridge-webos-tv](https://www.npmjs.com/package/homebridge-webos-tv)

That was pretty much one of the main reasons for me for using your plugin.

**Comment by konradknitter** [comment]
I successfully reached TV icon, replacing generic house icon.
Had to remove services from getServices(), requiring manual adding of device, and linking tvService with Accessory.

I couldn't reproduce showing no answer.
I will publish it after testing with configurable inputs.

**Comment by konradknitter** [comment]
Part of 0.2.0 delivery.
@Staubgeborener please feel free to retest it, and follow up with feedback.

**Comment by Staubgeborener** [comment]
Updated to 0.2.0:

With my old config:

> [4.11.2020, 14:58:55] [PhilipsAndroidTV] Fetching applications
> [4.11.2020, 14:58:55] [PhilipsAndroidTV] Available applications: Wie Sie..., Play Store, YouTube, TED, maxdome, ...
> [4.11.2020, 14:58:55] TypeError: Cannot read property 'includes' of undefined
>     at PhilipsAndroidTvAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/src/index.ts:386:46)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:421:28)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (_stream_readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> [4.11.2020, 14:58:55] Got SIGTERM, shutting down Homebridge...

So i tried to change my config a little bit:
```json
        {
            "accessory": "PhilipsAndroidTV",
            "name": "PhilipsAndroidTV",
            "ip": "192.168.178.XX",
            "macAddress": "XX:XX:XX:XX:XX:XX",
            "apps": [
                "Netflix"
            ],
            "alternativePlayPause": true
        },
```

The log output:

> [4.11.2020, 15:03:44] [PhilipsAndroidTV] Fetching channels
> [4.11.2020, 15:03:45] [PhilipsAndroidTV] Available Channels:
> [4.11.2020, 15:03:45] [PhilipsAndroidTV] Fetching applications
> [4.11.2020, 15:03:45] [PhilipsAndroidTV] Available applications: Wie Sie..., Play Store, YouTube, TED, maxdome, ...
> [4.11.2020, 15:03:45] [PhilipsAndroidTV] Publishing accessory
> [4.11.2020, 15:03:45] PhilipsAndroidTV 81F5 is running on port 39835.
> [4.11.2020, 15:03:45] Please add [PhilipsAndroidTV 81F5] manually in Home app. Setup Code: 031-45-154
> [4.11.2020, 15:03:49] [PhilipsAndroidTV] getCurrentActivity: unknown activities/tv structure: {}

What to do about the `unknown activities/tv structure: {}`? I can not add the TV in HomeKit, it  does not appear. But the 'TV does not response' (first screenshot) is still there in HomeKit.

**Comment by Staubgeborener** [comment]
Edit: Ok, the 'no response' message is a HomeKit Bug. I had to delete my whole home in HomeKit und recreate it. Now i can add the tv with your plugin. But `unknown activities/tv structure: {}` is still in the log. Maybe you can find out what this is? Buuuuuut all in all, the TV has now the tv icon, so this problem is basically solved.

**Comment by konradknitter** [comment]
Hey,

This log is what we found in #2, that on his TV, we cant fetch current open channel. 

I will suspend this warning, depending on TV API version. Could you check your API version?

You can check it via browser:
http://TV-IP:1925/system

**Comment by Staubgeborener** [comment]
```json
api_version |  
-- | --
Major | 6
Minor | 4
Patch | 0
```
Btw for your readme: This plugin works finde with my "65OLED804/12".
