### ISSUE TITLE
Proble

### ISSUE THREAD

**Issue by jemagnie** [konradknitter/homebridge-philips-android-tv#14]
**Describe Your Problem:**
Hi,

I have 2 issues, first I have 4 accessories in HomeBridge for my TV : 
- MuteSwitch
- VolumeBuble
- TV
- Volume TV
But in HomeKit the accessories as Volume Tv doest not appear
And my second issue is this log

Thanks and happy Christmas 

**Logs:**

getCurrentActivity: unknown application:{"component":{"packageName":"org.droidtv.tv.tptvservice","className":"NA"}}
getCurrentActivity: unknown activities/tv structure: {}

**Plugin Config:**

```
{
    "bridge": {
        "name": "Homebridge 2EE2",
        "username": "*",
        "port": *,
        "pin": "*"
    },
    "accessories": [
        {
            "name": "Living Room TV",
            "ip": "*",
            "macAddress": "*",
            "apiUser": "*",
            "apiPass": "*",
            "alternativePlayPause": true,
            "dedicatedMuteSwitch": true,
            "dedicatedVolumeLightbulb": true,
            "printConfiguredApps": false,
            "registerAsDefaultAccessory": false,
            "apps": [
                "Youtube",
                "Netflix"
            ],
            "accessory": "PhilipsAndroidTV"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.1.7
* **Node.js Version**: v14.15.3
* **NPM Version**:  6.14.9
* **Operating System**:  macOS

**Comment by konradknitter** [comment]
TV Volume can be controlled on iOS only via Remote Widget.

Those logs indicate nothing wrong, if plugin works correctly.


Best regards,
Konrad Knitter
