### ISSUE TITLE
Use favorite channels as input sources

### ISSUE THREAD

**Issue by r1sim** [konradknitter/homebridge-philips-android-tv#15]
## Is your feature request related to a problem? Please describe:

This plugin allows the user to define input sources for homekit. In my case I just want to add all the channels I usually watch. I already marked these channels as favorites on my tv. 

It would be great if there was an option to use the favorite channels as input sources for homekit. This would make the setup and the maintenance of the plugin configuration much easier.

## Describe the solution you'd like:

I can imagine two possible behaviours for this feature.
- Use favorites of TV **OR** channel list defined in options under `List of Channels`
- Extend list of favorites by list of channels defined in options under `List of Channels`

### Configuration:

The configuration section `List of Channels` could be extended by a check box. Something like this:
![image](https://user-images.githubusercontent.com/9327096/103143695-0b597300-471c-11eb-92f8-130634900fb8.png)

Optionally it would be possible to hide the channel array if the checkbox is checked using the [conditional display option of homebridge](https://developers.homebridge.io/#/config-schema#conditional-display).

The `config.schema.json` file could look like this:
```json
...
            "channels": {
                "title": "List of Channels",
                "type": "object",
                "properties": {
                    "useFavorites": {
                        "title": "Use favorites from TV",
                        "description": "If enabled plugin will load the favorite channels from the tv as homekit input sources.",
                        "type": "boolean",
                        "default": "false"
                    },
                    "channels": {
                        "title": "List of Channels that will be added as Input in HomeKit.",
                        "type": "array",
                        "condition": {
                            "functionBody": "return model.channels.useFavorites === true;"
                        },
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
...
```

I never actually developed homebridge plugins, so I'm not really sure if the snipped above would work. I also think that this solution would result in a breaking change because the `channels` property would change its path. Maybe there is a better solution for this.

### Technical aspects:
The API [already has an endpoint](https://github.com/eslavnov/pylips/wiki/Channel-list-(GET)) to get the favorite channels. This endpoint seems to be very similar to the "all channels" endpoint, which is already implemented in the application.

Depending on the configuration we could use this endpoint to load or extend the list of input sources while loading the plugin.

**Comment by konradknitter** [comment]
Good idea! I will implement it in free moment.

**Comment by konradknitter** [comment]
Unfortunately both my TVs for get of favorite lists return nothing interesting, even though I have favorite channels configured.

[12/29/2020, 4:04:55 PM] [Test Living Room TV] {"version":7,"id":"all","type":"MixedSources","medium":"mixed","name":"all","channels":[]}

**Comment by r1sim** [comment]
I also just tried that on my PUS7303 and also get this type of response using the `/channeldb/tv/favoriteLists/all` endpoint.
When I call `/channeldb/tv/favoriteLists/1` I get this response:
```json
{
  "version": "768",
  "id": "1",
  "type": "MixedSources",
  "medium": "mixed",
  "name": "Favourites\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
  "channels": [
    {
      "ccid": 1648,
      "preset": "1"
    },
    {
      "ccid": 1649,
      "preset": "2"
    },
    {
      "ccid": 1650,
      "preset": "3"
    },
    {
      "ccid": 1647,
      "preset": "4"
    },
    {
      "ccid": 1646,
      "preset": "5"
    },
    {
      "ccid": 1645,
      "preset": "6"
    },
    {
      "ccid": 1671,
      "preset": "7"
    },
    {
      "ccid": 1670,
      "preset": "8"
    },
...
  ]
}
```

The `preset` numbers are the channel numbers of my favorites, but I have no Idea what the `ccid` numbers refer to.

**Comment by konradknitter** [comment]
Good lead!

Seems CCID have to be mapped from those in channeldb/tv/channelLists/all.

As its not easy replacement, I will follow up it in next days.

**Comment by r1sim** [comment]
Alright, I'd also be willing to create a PR if you want.

**Comment by konradknitter** [comment]
Seems to work with 0.4.9

**Comment by r1sim** [comment]
Awesome! I just tried it in my environment, and it works perfectly! Thank you :)
