### ISSUE TITLE
Override the request timeout setting

### ISSUE THREAD

**Issue by nils-hde** [konradknitter/homebridge-philips-android-tv#18]
Every night I turn the power off for my TV devices using a power plug. Thus the TV will of course stop responding for a couple of hours. However, the plug-in seems to give up on connecting:

`Tried to make TV over 100 requests and failed. [...]`

How can I override this setting to *not* stop the plug-in from trying?

**Comment by Staubgeborener** [comment]
Currently not possible, that would need a new PR.
Its coded in [PhilipsTV.ts](https://github.com/konradknitter/homebridge-philips-android-tv/blob/master/src/PhilipsTV.ts#L55):
```typescript
if (counter === 100) {
    this.warn('Tried to make TV responsive over 100 requests and failed. Please double check configuration.');
    return;
}
```
This would required a new option (boolean) for the config like `"keeptrying": true`.

```typescript
if (counter === 100 && keeptrying === false)
```

**Comment by konradknitter** [comment]
Hi, added new option: wakeUntilAPIReadyCounter, if you set it as -1 it should never give up. Let me know if it will solve your use case.
