### ISSUE TITLE
"The plugin 'homebridge-philips-android-tv' slows down requests made to homebridge!"

### ISSUE THREAD

**Issue by 71z0** [konradknitter/homebridge-philips-android-tv#20]
In the Homebridge Protocol I always get the following error messages:

> [21/01/2021, 13:19:46] The plugin 'homebridge-philips-android-tv' slows down requests made to homebridge! The read handler for the characteristic 'Mute' was slow to respond!
> [21/01/2021, 13:19:53] The plugin 'homebridge-philips-android-tv' slows down requests made to homebridge! The read handler for the characteristic 'Mute' didn't respond at all!. Please check that you properly call the callback!

Environment:
* Plugin Version: v0.4.11
* Homebridge Version: v1.3.0-beta.47
* Node.js Version: 15.5.0
* NPM Version: 7.3.0
* Operating System: Raspbian GNU/Linux 10 (buster)

Is there a way to change that?

**Comment by konradknitter** [comment]
Hey,

That’s a new thing.
Code request handling is asynchronous. So it shouldn’t be a problem.

Detecting callback not called might be leak, I will have to check this new homebridge. Will get back in few days.

Best regards,
Konrad Knitter

**Comment by 71z0** [comment]
Wow, that's what I call instant feedback ;-) Thanks!
The plugin is connected it to a Philips 55OLED804.

**Comment by BETEP-ok** [comment]
we'll... my 2 cents: issue persist in the release of HB 1.3x:

[3/2/2021, 11:08:20 AM] [homebridge-philips-android-tv] This plugin slows down Homebridge. The read handler for the characteristic 'Mute' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 11:08:25 AM] [homebridge-philips-android-tv] This plugin generated a warning from the characteristic 'Active Identifier': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.

**Comment by konradknitter** [comment]
I few fixed missing callbacks calls in case lack of answer in 0.4.14.

**Comment by konradknitter** [comment]
In new version, I believe I catch all such problems. If you see any new issue - please raise new issue. I will close this one.
