### ISSUE TITLE
Change App

### ISSUE THREAD

**Issue by mikicof** [konradknitter/homebridge-philips-android-tv#21]
Hi!

I know it's a noob question but, how do I change the application on the TV? They show up as group accessory, and I could make them show on frontpage but I cannot control them, as they don't have a Power On button.

Also, as a suggestion, in the meantime the HDMI list is not available, I think is a good idea to use the play/pause button as an Input button that shows the external input tray in the tv.
I have it configured in my broadlink IR that way so I can change input. Maybe make it configurable via a toggle.

Thank you!

**Comment by konradknitter** [comment]
Hi,

Remove and add again TV in Home app. Then you can scroll thru channels list.

Each time you change input list this has to be redone - unfortunately limitations of platform.

Suggestion for custom replacement of remote inputs sounds easy to do, so I will add it in next release. Thanks for feedback.

Best regards,
Konrad Knitter

**Comment by mikicof** [comment]
That was it! Now they show up on channel list.

Thank you for your quick reply! I'll be looking forward for the input selection ;)
