### ISSUE TITLE
Selecting "Use favorite list" is not considering the input of "Favorite list ID"

### ISSUE THREAD

**Issue by pphhiihhaarr** [konradknitter/homebridge-philips-android-tv#22]
**Describe The Bug:**
No matter which favorite list ID I enter, always the one with ID == 1 is taken. I have 2 lists on my TV. ID 2 is never taken even though I enter it in the config and do a restart.

**To Reproduce:**
Enter a different ID (not 1) of an existing favorite list...and every time the one with ID == 1 is taken

**Expected behavior:**
the corresponding list should be taken. when I enter list ID 2 I expect list 2 is taken.

the request may not be hard coded with "1" but with a variable matching the ID I enter in the config.
in index.js:
request(this.buildRequest('channeldb/tv/favoriteLists/1', 'GET', '')

**Plugin Config:**
"channels": {
                "useFavorites": true,
                "favoriteListId": "2",
                "includeAll": false
            }

* **Plugin Version**:
* **Homebridge Version**: 1.1.7
* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.10
* **Operating System**:  Raspbian

**Comment by konradknitter** [comment]
Hi, sorry for long delay - should be now properly handled in 0.9.0+. Please let me know if your use case works now.
