### ISSUE TITLE
The plugin has broken with the 1.3 Homebridge  update

### ISSUE THREAD

**Issue by josetomas95** [konradknitter/homebridge-philips-android-tv#23]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by marcoschmidt79** [comment]
the plugin is working for me, also i have one error: Feb 20 17:12:55 homebridge homebridge[29287]: [20.2.2021, 17:12:55] [homebridge-philips-android-tv] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

**Comment by BETEP-ok** [comment]
confirm.... was thinking it is connected with an update of android TV but feels more than the 1.3 HB update

**Comment by konradknitter** [comment]
I few fixed missing callbacks calls in case lack of answer in 0.4.14.

**Comment by konradknitter** [comment]
In new version, I believe I catch all such problems. If you see any new issue - please raise new issue. I will close this one.
