### ISSUE TITLE
SET handler returned write response value, though the characteristic doesn't support write response

### ISSUE THREAD

**Issue by jonas240** [konradknitter/homebridge-philips-android-tv#25]
Hi,
I'm using the newest plugin and homebridge (HOOBS) version.

I get the following error no matter what I do. The TV still does what it shoud like switching apps. Some examples:

```
[Philips TV 01B0@Philips TV@Active Identifier] SET handler returned write response value, though the characteristic doesn't support write response
[Philips TV 01B0@Philips TV@Active Identifier] SET handler returned write response value, though the characteristic doesn't support write response
[Philips TV 01B0@Philips TV@Active Identifier] SET handler returned write response value, though the characteristic doesn't support write response
[Philips TV 01B0@Philips TV@Active Identifier] SET handler returned write response value, though the characteristic doesn't support write response
[Philips TV] Switching channel to: Das Erste HD
[Philips TV 01B0@Philips TV@Active Identifier] SET handler returned write response value, though the characteristic doesn't support write response
[HOOBS 5BFD@Philips TV@Philips TV Volume Bulb@Brightness] SET handler returned write response value, though the characteristic doesn't support write response
```

Has somebody any idea what I'm doing wrong?

Thank you so much! Great plugin!
Jonas

**Comment by konradknitter** [comment]
Sounds like it's something I was doing wrong in code. I
Could you retest your scenario using new version of plugin?

**Comment by jonas240** [comment]
Version 0.10.0 fixed it for me. However, I used a clean new plug-in install and manual configuration as HOOBS does not use/support config UI. So I can not tell if a simple update and using the "accessory configuration" instead of the "platform configuration" would fix it.

For all HOOBS users: You need to paste the "platform configuration" manual into the JASON as the plugin configuration always pastes into "accessories" for this plugin. (Maybe something you could change in the future @konradknitter)

Testing this, I found out that "apps" doesn't work for me anymore. I open a new issue for that.

Just out of interest, could you provide some insights why you changed from "accessory" to "platforms"? @konradknitter

**Comment by konradknitter** [comment]
You should still be able to use _accessory_ configuration in 0.10.0.
About switch, I've added config-ui additions, plan to integrate ambilight to same plugin - have shared configuration for many TVs. First step to this direction.

**Comment by jonas240** [comment]
@konradknitter Thanks for the insight. I figured accessory configuration would work, just thought I could change it now to platform configuration to save time later on
