### ISSUE TITLE
Help needed: Volume control using remote

### ISSUE THREAD

**Issue by jonas240** [konradknitter/homebridge-philips-android-tv#26]
Hi,

I'm having issues/problems with volume control. Probably just a user error by myself.
I can't find how to use volume control in iOS. Using the volume bulb is no problem. However, how do I use the 'remote' to change volume?
As far as I understand it:
I press this button:
![image](https://user-images.githubusercontent.com/68380809/111195737-dd6a2900-85bc-11eb-843f-4892a8758f5e.jpeg)
That's the remote I get:
![image](https://user-images.githubusercontent.com/68380809/111195779-e8bd5480-85bc-11eb-9f1a-9f812e664987.png)

However no option to control the volume. 

Homebridge and plugin are up to date. TV is 50PUS8545 (2020) Android TV

Thank you so much for help! Great plugin nevertheless!
Jonas

**Comment by konradknitter** [comment]
Use phone volume up and down 


Best regards,
Konrad Knitter
