### ISSUE TITLE
Sound Volume doesn't work

### ISSUE THREAD

**Issue by Yomguigui** [konradknitter/homebridge-philips-android-tv#3]
**Describe The Bug:**
The button volume on iPhone doesn't modify the volume of the TV when the widget is enable

**To Reproduce:**
I have restart servers, and iPhone but it doesn't work.

**Expected behavior:**
When I press the button volume on the left of the iPhone, when the widget TV is enable 

**Logs:**
The logs doesn't log when I press button volume

**Plugin Config:**

`` 
"accessories": [
        {
            "accessory": "PhilipsAndroidTV",
            "name": "Philips TV Oled",
            "ip": "YYY",
            "macAddress": "ZZZ",
            "apiUser": "XXX",
            "apiPass": "YYY",
            "apps": [
                "Plex",
                "Netflix",
                "YouTube",
                "Guide TV"
            ],
            "channels": [
                "TF1",
                "France 2",
                "M6",
                "BFM TV",
                "LCI"
            ]
        }
    ]``

**Environment:**

* **Plugin Version**: V2.0
* **Homebridge Version**: 1.2.3
* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.5
* **Operating System**: Raspbian

Thank's for this great plugin, the first for me which works fine with channels, apps AND widget.

**Comment by konradknitter** [comment]
Hi, thanks for reporting

actually I didn't get yet how to control volume from iPhone. :)
It works properly in Homebridge UI, but couldn't figure out where it supposed to be on iPhone.

Have you seen volume working in an other plugin?

**Comment by konradknitter** [comment]
Added missing attribute, and volume control works from iPhone Remote App.

`        this.tvSpeaker.setCharacteristic(hap.Characteristic.VolumeControlType, hap.Characteristic.VolumeControlType.ABSOLUTE);`

I will publish it today thanks.

**Comment by konradknitter** [comment]
Delivered as part of 0.2.2 drop

**Comment by Yomguigui** [comment]
Thanks a lot, the volume is now functional !!
However the status of the device in the home application doesn't work....
This appear with the v0.2.2n, not initially with the 0.2.0.
Any idea ?

**Comment by konradknitter** [comment]
Hey,

Great to hear that 👍 

Do you mean that device is offline, when its on?
Or that cant be connected/not responsive?

Compared to 0.2.0, I’ve added 10 sec interval to check status to keep those up to date ( on, off, which channel is set) - because it was losing synchronization when normal remote is used.

**Comment by Yomguigui** [comment]
The status appears in uptdate, and after that the device is not connected / not responsive.
Maybe 10 sec of interval is to long...
Thanks

**Comment by Yomguigui** [comment]
Tested v0.2.3, all works fine.
Great job 👍
Thanks a lot !
