### ISSUE TITLE
Can find username and pw (I’m using homebridge and I don’t have python)

### ISSUE THREAD

**Issue by argevany7** [konradknitter/homebridge-philips-android-tv#32]
I can find user name and password, I’m using the plugin in the homebridge website and I don’t have python. How can I do that?

**Comment by Staubgeborener** [comment]
You **have** to install python in order to get the username/password.
Here is a tutorial: https://github.com/suborb/philips_android_tv/issues/36#issuecomment-795208875

**Comment by argevany7** [comment]
How to connect the python and the homebridge, it runs on node jams I think

**Comment by Staubgeborener** [comment]
You don't "connect" python and homebridge. It also doesn't matter how homebridge is installed either, as it is independent. 
i.e. you have one system with a homebridge installation. Inside this system you install [python3](https://linuxize.com/post/how-to-install-python-3-9-on-debian-10/) (url may vary depending on the distribution, this is an instruction for debian).
You simply just follow my tutorial above. Just ignore the fact with the homebridge installation, it has nothing to do with that. i.e. you could also get the username/password with another system which didn't even have homebridge installed (for example a windows system. Or a mac os system. Or a linux/uni system. Or [insert any os here]).

**Comment by argevany7** [comment]
But when I try to run one of the commends on your tutorial I get an error

**Comment by argevany7** [comment]
I’ve downloaded python on my pc, but when I try to put any of the commends I get syntax error

**Comment by argevany7** [comment]
This is so hard and doesn’t clear 😩

**Comment by argevany7** [comment]
Why is that so hard and not clear😩😩

**Comment by Staubgeborener** [comment]
It's not hard and its **_very_** clear described in my tutorial above. It's done in two minutes. There is so many stuff which **_you_** not share. 

1. What is the system which is running homebridge?
2. What is the system where you try to run python?
3. WHAT are the commands you tried and WHAT are the errors (syntax errors) you receive?

I don't have a crystal ball neither.

**Comment by argevany7** [comment]
I run homebridge on node js.
I’ve downloaded python from the official website.
Node js says that the commend is not part of the language, 

what should I do after I’ve downloaded python?
Should I add the plug-in via homebridge website?
I tried but I couldn’t find the username and password
How do I use a python plugin with node js?

Btw I appreciate the help men

**Comment by Staubgeborener** [comment]
Node js is a runtime engine, not a operation system. Question 1 and 2 refers to your operating systems.

**Comment by argevany7** [comment]
I don’t use an operation system I am very new to that and I don’t know how to do it

**Comment by Staubgeborener** [comment]
You _are_ using a operation system. Homebridge has to be installed on a device.

**Comment by argevany7** [comment]
Ohhh, I’m using windows😅

**Comment by argevany7** [comment]
Big brain moment lol

**Comment by Staubgeborener** [comment]
And homebridge is installed on windows? Could you please link the tutorial you used for this

**Comment by argevany7** [comment]
Yes it is on windows 
Tutorial: https://youtu.be/5mxhAgryuVo

**Comment by Staubgeborener** [comment]
Ok, we have to do those linux commands in windows style. Try this:

1. Create a new file called `philips.py` (and please, check if the file extension truly is `.py` and not `.py.txt` or something like this), the content of this file exactly [this here](https://raw.githubusercontent.com/suborb/philips_android_tv/master/philips.py)
2. Save the file on your desktop
3. Create a new file called `requirements.txt` and copy [this](https://github.com/suborb/philips_android_tv/blob/master/requirements.txt) here inside this file, save the file on your desktop
4. check the path of you pip, it should be automatically installed with python 3: https://stackoverflow.com/a/41501815, lets assume the path of pip3 is `C:\path\to\python\Scripts\pip3` 
5. Open `cmd`
6. What is your python version? Type `python --version` I hope you installed python 3 and not python 2. If it is python 2: Install python 3.
7. Now in `cmd` use `C:\path\to\python\Scripts\pip3 C:\path\to\requirements.txt`
8. Turn you tv on
9. After that in `cmd`: `python3 C:\path\to\philips.py --host <YOUR_IP_ADDRESS> pair`
**And yes, <YOUR_IP_ADRESS> is the ip of your philips tv WITHOUT `< ... >`**
10. Your TV shows a code, be fast, the code will disappear
11. Type the code on your tv into your terminal
12. You get a username and a password.

Problems? Please exactly where and what happens WITH error messages/codes.

**Comment by argevany7** [comment]
THANK YOU SO MUCH
I don’t even know who are you but I love you

**Comment by argevany7** [comment]
Hey, I tried and when I write on cmd python—version it says “python is not recognized as an external or external command operable program or batch file”

**Comment by argevany7** [comment]
And I’ve created the philips.py with IDLE python is that ok?
I’m using pyrhon 3.9

**Comment by argevany7** [comment]
All my questions above are solved,
But when I tried to run the script I got some errors see picture: 
![Uploading F4CF049E-1B16-412E-BE02-C06DC8376DAA.jpeg…]()

**Comment by Staubgeborener** [comment]
You didn't upload a picture. You just linked your own issue.

**Comment by argevany7** [comment]
![D092BD9B-4E91-4BC6-8C03-A064744AFE93](https://user-images.githubusercontent.com/84562325/119219374-f677e480-baed-11eb-9a52-03edca8e1d71.jpeg)

**Comment by argevany7** [comment]
Now that’s ok?

**Comment by Staubgeborener** [comment]
Please give me the command you tried, post the whole error message (no screenshot, just copy paste it here in ! a `code block` !).
Is 10.0.0.22 **really** the ip of your tv? What tv model (exactly the model, as accurately as possible) do you use?

**Comment by argevany7** [comment]
I’m not near my pc right now but I did as you told me, I created a philips.py file in python and I run it.
The code I used is in the link you gave me in step number 1.
My tv ip is 10.0.0.20 : see image
the model is 40pfh4100/88

**Comment by argevany7** [comment]
![ECF4C679-6633-440F-8051-28673B2E89FC](https://user-images.githubusercontent.com/84562325/119221700-2ed0f000-baf9-11eb-9d18-aa9413a63608.jpeg)

**Comment by Staubgeborener** [comment]
Please verify, that you installed the requirements.txt with pip. Also verify, that you use python3 and not python2. 
`python3 C:\path\to\philips.py --host <YOUR_IP_ADDRESS> pair`
-> python3 at the beginning guaranteed that you use python3. If you just use `python [...]` instead, it will maybe use python3 - but also maybe 2, depending on your system and `PATH` variable. All of those question are to be sure, that you don't have dependency issues.

Also: Your computer and the tv have to be in the same network. Your tv has to be turned on before, when you use the python-command. If the tv is turned off, you don't get a connection.

Maybe the api of your tv doesn't support this or doesn't even have a working api. Turn you tv on and check this "websites" with your browser:

```
10.0.0.22:1925/1/system
10.0.0.22:1925/6/system
10.0.0.22:1926/1/system
10.0.0.22:1926/6/system
```

One of those should would, please post the stuff here. If all of them gives you "Unable to connect error", then you've got no working api on this tv.

**Comment by argevany7** [comment]
I’m using python 3 for sure, 
How do I install requirements with pip?

I can control my tv via Philips app.
I’ll try those websites and update you

**Comment by Staubgeborener** [comment]
> How do I install requirements with pip?
 I told you how.

**Comment by argevany7** [comment]
Ok, the tv is paired and everything works wonderfully but then u turn off the tv and it changes the TVs username and password

**Comment by Staubgeborener** [comment]
Great to hear that you figure it out. I think you can close this issue here and ask your manufacturer.

Maybe your new problem is TV specific as I hear this kind of issue the first time. Normally you just grep the username and password like you did, set up this plugin and never do this again.

**Comment by konradknitter** [comment]
Thanks a lot @Staubgeborener for supporting this issue.

I added pairing directly to plug-in via UI to simplify the process and meet verification requirements.

Seems nothing more can be done in this issue, so I will close it.
