### ISSUE TITLE
0.10.0 | Siri respons "device TV doesn't responde" however TV does responde

### ISSUE THREAD

**Issue by jonas240** [konradknitter/homebridge-philips-android-tv#35]
**Describe The Bug:**
Hi,
when I ask Siri to turn on/off the device, she always responds something like "device doesn't respond" and after that she turns the TV on/off without flaws. So this bug is rather cosmetic that functional.

**To Reproduce:**
As Siri to turn on/off TV

**Expected behavior:**
TV turns on/off but without the "device is not responding" message.

**Screenshots:**

These are in German, but I guess even a non-german speaker would understand what I mean (I hope):
Probaby a second after this request the TV in fact does turn off/on, while turning off is faster than turning on. However, I guess thats expected.

![IMG_0308](https://user-images.githubusercontent.com/68380809/120663411-49588100-c48a-11eb-8ced-ae2698ba1b1c.jpg)
![IMG_0309](https://user-images.githubusercontent.com/68380809/120663429-4c537180-c48a-11eb-8f5a-66957e25872e.jpg)

**Environment:**

* **Plugin Version**: 0.10.0
* **Homebridge Version**:  1.3.3
* **Node.js Version**:  14.17.0
* **NPM Version**:  3.3.5
* **Operating System**: Raspbian

**Comment by konradknitter** [comment]
I reproduced it, but have no idea what causes that. I had not using Siri myself to control TV. Did it showed after plug-in update?

**Comment by jonas240** [comment]
I have to admit, I hardly used Siri for my TV before, so I actually can't tell, sorry.

Further to that issue I'm receiving a ton of logs like below:

```
3.6.2021, 17:02:26 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan. 
3.6.2021, 17:02:26 [PhilipsAndroidTV] [TV] Start responding again. 
3.6.2021, 17:03:36 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan. 
3.6.2021, 17:03:36 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:04:46 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:04:47 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:05:56 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:05:57 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:07:06 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:07:07 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:08:16 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:08:17 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:09:26 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:09:27 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:10:36 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:10:37 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:11:46 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:11:47 [PhilipsAndroidTV] [TV] Start responding again.
3.6.2021, 17:12:56 [PhilipsAndroidTV] [TV] Stop responding. Trying to wake over lan.
3.6.2021, 17:12:57 [PhilipsAndroidTV] [TV] Start responding again.
... [and so on]
```

All while I'm watching Netflix :)

Maybe [https://github.com/AlexGustafsson/homebridge-wol/issues/85](url) can be of insight. This plugin uses something like "return early" to fix a problem when a device is usually not responding as fast HomeKit/Siri needs a device to respond. An example is my server. I turn my server on by the WOL plugin, but it needs about 30s till its actually on. This option prevents the usual "not responding" after I switch the server to "on".

**Comment by konradknitter** [comment]
I tested it, immediate calling callback (not waiting for response) solved the issue. I will push it in few moments.

About prints, ok - I think I over do by calling WoL in case of TV stop responding. (in sleep mode in example... there is no point - it will be important when client wants to turn TV on) - so I've remove it in next update.

But looking at those logs, I think there might be another Exception - I will add in next update additional logs for that when using "debug" flag true in Platform config.

**Comment by jonas240** [comment]
Using 0.10.6. Works now as expected.
