### ISSUE TITLE
0.10.2 | Can't turn TV off

### ISSUE THREAD

**Issue by jonas240** [konradknitter/homebridge-philips-android-tv#37]
**Describe The Bug:**

Hi, I just updated to 0.10.2, and now I cannot turn my TV off. 

I turned it on using HomeKit. Now if I use HomeKit or the TV IR remote to turn the TV off it just turns itself on again after about one second. 

So I unplugged the TV. After connecting it again, it turned itself on again. Now I was able to turn the TV off using the TV remote.

If I turn the TV on using the TV remote, I am able to turn the TV off.

For some other reasons I have trouble turning the TV off using HomeKit, if I turned it on using the remote.

**Logs:**

```
.6.2021, 14:57:18 [PhilipsAndroidTV] [TV] TV has been turned off.                              //by TV remote
4.6.2021, 14:57:18 [PhilipsAndroidTV] [TV] TV volume has been changed to 0%.
4.6.2021, 14:57:23 [PhilipsAndroidTV] [TV] TV has been turn on.                                //I didn't do that
4.6.2021, 14:57:23 [PhilipsAndroidTV] [TV] TV volume has been changed to 28%.
```

**Environment:**

* **Plugin Version**: 0.10.2
* **Homebridge Version**: 1.3.3
* **Node.js Version**: 14.17.0
* **NPM Version**: 3.3.5
* **Operating System**: Raspbian

**Comment by konradknitter** [comment]
10.0.3 should fix it.

**Comment by jonas240** [comment]
Using 0.10.6. It works as expected
