### ISSUE TITLE
Error: MAC Address is not set or not proper MAC address.

### ISSUE THREAD

**Issue by XavCamp** [konradknitter/homebridge-philips-android-tv#38]
Hi, thanks for the hard work on this great plugin!

**Describe The Bug:**
In the logs there is an error about mac address:
> MAC Address is not set or not proper MAC address.

**To Reproduce:**
That's when you provide a mac address in the config.

I think it's because in https://github.com/konradknitter/homebridge-philips-android-tv/blob/master/src/PhilipsTVPlatform.ts#L41
it should be `if (!this.mac ...`

**Expected behavior:**

**Logs:**

```
04/06/2021, 18:20:55 [PhilipsAndroidTV] Initializing PhilipsAndroidTV platform...
04/06/2021, 18:20:55 [PhilipsAndroidTV] [Living Room TV] MAC Address is not set or not proper MAC address.
```

**Plugin Config:**

```json
{
            "platform": "PhilipsAndroidTV",
            "plugin_map": {
                "plugin_name": "homebridge-philips-android-tv"
            },
            "tvs": [
                {
                    "ip": "192.168.86.27",
                    "mac": "[my valid mac address]",
                    "name": "Living Room TV",
```

**Environment:**

* **Plugin Version**: 0.10.6
* **Homebridge Version**: not sure, using HOOBS 3.3.5
* **Node.js Version**: 12.14.1
* **NPM Version**: 6.13.4
* **Operating System**: HOOBS on Raspberry Pi

**Comment by konradknitter** [comment]
@XavCamp MAC setting is optional, so line is okay.
You need to set mac( that condition is met) and it has to fall to meet regex:  /^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$/

Check if your MAC falls here.
https://regexr.com/

Or maybe why it doesn't? (AA:BB:DD:CC:EE:FF works)

**Comment by XavCamp** [comment]
Ok I see, the issue is that my MAC address was using lowercase letters, not
uppercase. I don’t think case matters for MAC addresses, but I’ll fix my
config.
Thanks!
