### ISSUE TITLE
Channels/apps doesn't update automatically 

### ISSUE THREAD

**Issue by Yomguigui** [konradknitter/homebridge-philips-android-tv#4]
Describe The Bug:
The status of the power TV is functional, but the channels / app doesn't update automatically when the TV channels is changed by the original remote control. It's work when the change is done by the iPhone, not when it's done by remote control TV.

Plugin Config:

"accessories": [ { "accessory": "PhilipsAndroidTV", "name": "Philips TV Oled", "ip": "YYY", "macAddress": "ZZZ", "apiUser": "XXX", "apiPass": "YYY", "apps": [ "Plex", "Netflix", "YouTube", "Guide TV" ], "channels": [ "TF1", "France 2", "M6", "BFM TV", "LCI" ] } ]

Environment:

Plugin Version: V2.2.3
Homebridge Version: 1.2.3
Node.js Version: v12.16.3
NPM Version: v6.14.5
Operating System: Raspbian

**Comment by konradknitter** [comment]
Hey,

it has been implemented in 0.2.3 to double check state every 10 seconds.
I noticed by #6 logs that some TV doesn't report any activity over REST API. I don't have any alternative solution. 

Do you see those mentioned warnings in logs?

**Comment by Yomguigui** [comment]
ok, thanks for the response.
Logs says always that : [2020-11-6 21:59:45] [Philips TV Oled] getCurrentActivity: unknown application:{"component":{"packageName":"org.droidtv.playtv","className":"org.droidtv.playtv.PlayTvActivity"}}
However channels or apps selected...

This function works with the plugins : Homebridge Plugin for Philips Tv Api 6.

**Comment by konradknitter** [comment]
{"component":{"packageName":"org.droidtv.playtv","className":"org.droidtv.playtv.PlayTvActivity"}}

TV/"Channels sounds like TV/Channel App.
Funny that on my TV is either "NA" on one, or "zapster" on another. 

I will add this name also to ask for channel in next revision :)

**Comment by konradknitter** [comment]
0.2.5 contains only that change, try it - I hope at least channels will work (still 10 seconds timer to update)

**Comment by Yomguigui** [comment]
It Works fine !
Thanks a lot !
Great job !!
