### ISSUE TITLE
HomeKit State is only updated when opening the Home app

### ISSUE THREAD

**Issue by hatsuo** [konradknitter/homebridge-philips-android-tv#45]
First, thank you for this nice plugin!

I would like to have some automations based on whether the TV is turned on or off.

However, this does only work reliably when the TV is turned on or off using HomeKit.
When I turn the TV on or off by using the TV remote or CEC, the automations only trigger when I open the Home app and select a screen where the TV is shown, so it looks like the state is only fetched when it is explicitely requested by HomeKit.

Can this behaviour be changed?

**Comment by konradknitter** [comment]
State is checked periodically, if you know what could be added, it can be added to 

async checkStatus() {

function.
