### ISSUE TITLE
unknown activities/tv structure in HomeBridgelog

### ISSUE THREAD

**Issue by korgboll** [konradknitter/homebridge-philips-android-tv#6]
Hi, just trying this plugin out.

It seems to work but Im getting this error in the Homebridge-log

[PhilipsAndroidTV] getCurrentActivity: unknown activities/tv structure: {}

The config for the plugin is as below:
{
            "accessory": "PhilipsAndroidTV",
            "name": "AndroidTV",
            "ip": "10.0.1.15",
            "macAddress": "d8:13:99:dd:93:9d",
            "apiUser": "xxxxxxxx",
            "apiPass": "yyyyyyyy",
            "apps": [
                "Netflix",
                "YouTube",
                "Plex"
            ],
            "alternativePlayPause": true
        }

**Comment by eRJe79** [comment]
Same issue here. Message repeats every 10 seconds with 3 entries.

[11/6/2020, 18:49:04] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
[11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}

**Comment by konradknitter** [comment]
Hi, this log just indicates that when I ask what TV is presenting, it replies empty structure. 
My TVs reports app or channel. I received multiple comments that it returns nothing..

I limited this log occurrence to one per startup in 0.2.4 release.

**Comment by korgboll** [comment]
Great job! 
The update works fine, I only see it once now! 
Big thanks and keep up the good work!

**Comment by eRJe79** [comment]
I could not reproduce the event again. I confirm that it is only showing once at startup.

**Comment by Novi001** [comment]
> Same issue here. Message repeats every 10 seconds with 3 entries.
> 
> [11/6/2020, 18:49:04] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:14] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:24] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}
> [11/6/2020, 18:49:34] [55OLED854] getCurrentActivity: unknown activities/tv structure: {}

The same here. It does not matter whether the Homebridge is restarted with the TV switched on or the TV switched off. In addition, the TV only wakes up the 2nd time it’s pushen the Button on Homekit. TV is connected to WiFi. Everything else works perfectly.
If the TV is on, the entries are not generated. Can I bypass the countless logs? I am using the latest version 0.3.1.
Your Ambilight plug-in works fine.

**Comment by konradknitter** [comment]
I limited other logs as well, and added trying again SetOn TV in case of failure in 3 seconds (so if not works first time, will repeat after 3 seconds).
Please check if those solve your issues.

**Comment by Novi001** [comment]
Good morning K.,

and thank you for your quick response.
The messages in the log are now considerably fewer - great.
Switching on the TV now also works the first time - according to your built-in delay of 3 seconds. The TV can also be controlled without any problems. There is only one display error in HomeKit: TV is switched on, but the text says "no answer". If I turn the TV off again and then back on again, everything is perfect. Can you also add something here or is that due to HomeKit? I'll attach a few pictures. I installed your new version shortly before 7 a.m. and then restarted the Homebridge. From there the log begins.

Thank you very much and best regards,

Novi
![Bildschirmfoto 2020-12-09 um 07 54 34](https://user-images.githubusercontent.com/48883132/101597294-d1d3f880-39f6-11eb-85f7-d0be0a1284cf.png)
![Bildschirmfoto 2020-12-09 um 08 14 51](https://user-images.githubusercontent.com/48883132/101597300-d4cee900-39f6-11eb-929c-bbe6397bc1e1.png)
