### ISSUE TITLE
Cannot re-add TV in homekit

### ISSUE THREAD

**Issue by eRJe79** [konradknitter/homebridge-philips-android-tv#7]
I had setup homebridge-philips-android-tv succesfully. I was also able to add the Philips TV accessory in Homekit where I had some cotrols over the TV.

Once I removed the accessory from Homekit, I have not been able to add it again. I've reinstalled the plugin, rebooted Homebridge and Homekit without any success.

I can see that the plugin is connected to the TV but when I search for the accessory in Homekit, it does not show up anymore.

**Comment by eRJe79** [comment]
The workaround was to rename the TV in the plugin config.

**Comment by konradknitter** [comment]
Accessory to be presented as TV is registered as external accessory to Homebridge.
External Accessory can't be cleaned, neither have **any** persistent state.

So clean it - homebridge restart is needed.

Please attach logs if ever see notice this issue again.

**Comment by Staubgeborener** [comment]
I think this one can be closed.
> So clean it - homebridge restart is needed.

This is the solution. 

1. remove the TV from HomeKit
2. restart homebridge
3. (optional is this don't work for you) remove TV from HomeKit
3.1. remove the Plugin from homebridge (including config) 
3.2. restart homebridge
3.3. install plugin again and configure `config.json`
3.4. restart homebridge again

`External Accessory` are a little bit special...

**Comment by eRJe79** [comment]
I tried both ways and more without success. I thought it could perhaps be something remaining in the Home hubs so I restarted the Apple TV. I even did the pending software update to 14.2.
[HomeBridgeLog2.txt](https://github.com/konradknitter/homebridge-philips-android-tv/files/5530470/HomeBridgeLog2.txt)

As soon as I put in an unique name, homekit picks it up and I'm able to add the TV (again).

I've attached an extract of the homebridge log. I've filtered out the entries from other devices. Not sure if this is what you need as the info is limited. The log has 3 restarts. First with the original name from the plugin which fails. Second restart is with a name I have used previously which fails too. Third restart is a new name which works.

Let me know if you riquire other info.

**Comment by konradknitter** [comment]
All three times print
"Publishing accessory" indicates that external accessory have been registered,
also accessory uuid is based of name you provide, so always unique.

To be honest, I have no idea. We can escalate this to homebridge to get more support.
