### ISSUE TITLE
Speaker control

### ISSUE THREAD

**Issue by eRJe79** [konradknitter/homebridge-philips-android-tv#8]
In the desciption it's written that speaker control is supported. I've managed to control the volume via the remote widget on an iPhone but can I also have control directly in Homekit?

I would like to create a scenes with different audio preferences. For example audio muted when I use AppleTV and external speakers.

**Comment by konradknitter** [comment]
TV Speaker is registered to HomeKit as Television Speaker.
Everything from that point is up to apps using HomeKit.
I didn't manage to use Siri for this purpose.

Did you seen any other plugin that allows to do such?

We can add optional "lightbulb" as volume control as workaround.

**Comment by eRJe79** [comment]
I have tried https://github.com/98oktay/homebridge-philips-tv6#readme that has a volume control in the way I think you suggest a workaround. I have to say that I could not get that plugin to work. It would not connect to the TV so I don't really know how it would integrate.

**Comment by Staubgeborener** [comment]
@eRJe79 Installation of `homebridge-philips-tv6` is working the same way as this plugin. Its working on my 65OLED804/12 and 50PUS7303. With that plugin you get a lightbulb for volume controle in HomeKit like @konradknitter told you.

@konradknitter if you want to integrate this feature, then please as an **option**. Personally, the permanent display as "light is on" in Homekit bothers me

**Comment by eRJe79** [comment]
@Staubgeborener I've tried the plugin again but my log only says:
`[12/11/2020, 13:31:53] [Television2] Initializing PhilipsTV accessory...`

I can see that "light is on" display can be annoying. Personally I'm not so interested in being able to control the volume but being able to mute the TV speakers would be a real appreciated feature.

**Comment by konradknitter** [comment]
I'm back on issue, better late than never.

I am adding mute switch and volume lightbulb as options with flags dedicatedMuteSwitch, dedicatedVolumeLightbulb.
Hope those will be useful.
